#!/usr/bin/env bash
cat "${BASH_SOURCE[0]}"

# https://www.willmcgugan.com/blog/tech/post/ceo-just-wants-to-draw-boxes/
# ▁▁▁
# ▏ ▕
# ▔▔▔

# ┌──┬──┬──┐
# │  │  │  │
# ├──┼──┼──┤
# │  │  │  │
# ├──┼──┼──┤
# │  │  │  │
# └──┴──┴──┘

