#!/usr/bin/env bash
if ! (type xbacklight >/dev/null); then
	exec exitfail 'xbacklight command not found. Run `sudo apt install xbacklight`'
fi

if [[ "$1" == "up" ]]; then
	xbacklight -inc 10
else
	xbacklight -dec 10
fi

