#!/usr/bin/env bash
if ! (type xbacklight >/dev/null); then
	notify-send -t 2000 -u critical 'xbacklight command not found. Run `sudo apt install xbacklight`'
	exit 2
fi

# TODO: Check for this file: /etc/X11/xorg.conf

# Increase/descrease brightness
if [[ "$1" == "up" ]]; then
	xbacklight -inc 10
elif [[ "$1" == "down" ]]; then
	xbacklight -dec 10
fi

# Popup notification for brightness
brightness="$(xbacklight -get)"

# If the screen turns completely off, set birghtness to 1%
if (("${brightness%%.*}" == 0)); then
	xbacklight -set 1
fi

notify-send \
	-t 400 \
	-u normal \
	-h string:x-canonical-private-synchronous:brightness \
	"Brightness: ${brightness%%.*}%"

