#!/usr/bin/env bash
set -eou pipefail

cat <<-HEADER
================================================================================
BLIMITS
================================================================================
HEADER
blimits | sed -n -e '4p' -e "/$USER/p" | column -t
echo


