#!/usr/bin/env bash
# Example:
# https://github.com/tmux-plugins/tmux-yank/blob/master/scripts/helpers.sh
if (type xclip &>/dev/null); then
	xclip
	echo "Clipboard: '$(xclip -o)'"
elif (type pbcopy &>/dev/null); then
	pbcopy
	echo "Clipboard: '$(pbpaste)'"
else
	echo "Copy command not found." 1>&2
	exit 1
fi

