#!/usr/bin/env bash
# Examples:
# https://github.com/tmux-plugins/tmux-yank/blob/master/scripts/helpers.sh
# https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/clipboard.zsh

# Print all stdout to stderr
exec 1>&2

# Find copy command
if (type xclip &>/dev/null); then
	xclip || exit $?
elif (type pbcopy &>/dev/null); then
	pbcopy || exit $?
else
	echo "Copy command not found."
	exit 1
fi

# Check clipboard
copied="$(,paste)" || exit $?

newline=$'\n'
case "$copied" in
	*$newline*)
		cecho --fg yellow --bold 'Clipboard:'
		echo "$copied"
		;;
	*)
		cecho --fg yellow --bold -n 'Clipboard: '
		echo "'$copied'"
		;;
esac

# Copy to tmux buffer
if [[ -e "${TMUX%%,*}" ]]; then
	tmux set-buffer "$copied"
fi

