#!/usr/bin/env bash
# Example:
# https://github.com/tmux-plugins/tmux-yank/blob/master/scripts/helpers.sh
if (type xclip &>/dev/null); then
	xclip
	copied="$(xclip -o)"
elif (type pbcopy &>/dev/null); then
	pbcopy
	copied="$(pbpaste)"
else
	echo "Copy command not found." 1>&2
	exit 1
fi

echo "Clipboard: '$copied'"
if [[ -e ${TMUX%%,*} ]]; then
	tmux set-buffer "$copied"
fi

