#!/usr/bin/env bash

# Weather icons from:
# https://github.com/2KAbhishek/tmux2k/blob/main/scripts/weather.sh
declare -A weather_icons=(
	["Clear"]="󰖙"
	["Cloud"]=""
	["Drizzle"]="󰖗"
	["Fog"]=""
	["Haze"]="󰼰"
	["Mist"]=""
	["Overcast"]=""
	["Rain"]=""
	["Sand"]=""
	["Shower"]=""
	["Smoke"]=""
	["Snow"]=""
	["Sunny"]="󰖙"
	["Thunderstorm"]=""
	["Tornado"]="󰼸"
	["Windy"]="󰖝"
)

city="$(curl 'https://ipinfo.io/city' 2>/dev/null)"
printf "$city %s\n" "$(curl -sL "wttr.in/$city?format=1&u" 2>/dev/null)"
