#!/usr/bin/env bash
declare -r CURRENT_DIR="$(dirname "$(realpath.py "${BASH_SOURCE[0]}")")"
declare -r preview="$CURRENT_DIR/preview_scripts"
set -eo pipefail

# Uncomment to debug
#verbosity=1

# Get config
config=${1-default}
shift ||
if ((verbosity)); then
	echo "CONFIG: '$config'"
fi

# Get width/height
width=$(tput cols)
height=$(tput lines)

# Filter command
filter='cat'

# Default args
declare -A args
args['multi']="--multi"
# TODO: Dynamically set height based on current height
args['height']='--height 40%'
#args['height']='--height 100%'
args['tiebreak']='--tiebreak=length'
args['reverse']='--reverse'
args['info']='--info inline'
#args['keybind']='--bind=ctrl-s:toggle-sort'
args['keybind']='--bind=ctrl-c:clear-query'
args['bind']='--bind backward-eof:abort'

args['preview']="--preview '$preview/unknown {}'"
# TODO: Dynamically set preview-window size and position
args['preview-window']="--preview-window right:50%"
args['query']="--query='$@ '"
#args['exact']='--exact'
#args['tiebreak']='--tiebreak=index'
#args['expect']='--expect=ctrl-t,ctrl-v'

# Custom colorscheme
args['color']='--color '
args['color']+='fg:7,bg:233,fg+:39,bg+:236'
args['color']+=',hl:172,hl+:172'
args['color']+=',spinner:166,pointer:166,gutter:236,marker:214'
args['color']+=',prompt:123,info:123'
args['color']+=',border:33,preview-fg:7,preview-bg:235'

# Actions
# abort
# accept / accept-non-empty
# backward-char / backward-delete-char / backward-delete-char/eof
# backward-kill-word / backward-word
# beginning-of-line
# cancel
# change-prompt(...)
# clear-screen / clear-selection
# close
# clear-query
# delete-char / delete-char/eof
# deselect / deselect-all
# disable-search
# down
# enable-search
# end-of-line
# execute(...) / execute-silent(...)
# first / last
# forward-char / forward-word
# ignore
# jump / jump-accept
# kill-line / kill-word
# next-history
# page-down / page-up
# half-page-down / half-page-up
# preview(...)
# preview-down / preview-up
# preview-page-down / preview-page-up
# preview-half-page-down / preview-half-page-up
# preview-bottom / preview-top
# previous-history
# print-query
# refresh-preview
# reload(...)
# replace-query
# select / select-all
# toggle         / toggle-all
# toggle-in      / toggle-out
# toggle+down    / toggle+up
# toggle-preview / toggle-preview-wrap
# toggle-search  / toggle-sort
# unbind(...)
# unix-line-discard
# unix-word-rubout
# up
# yank


# TODO: More previews
	#--preview "'my-fzf-preview-git-diff {}'" \
	#--preview "'git show --color=always --numstat {1}'" \

case "$config" in
	default);;
	d|dir*) args['preview']="--preview '$preview/dir {}'";;
	fpga-image) args['preview']="--preview 'burst-show-image {2}'";;
	git-diff) args['preview']="--preview '$preview/git-diff {}'";;
	git-show) args['preview']="--preview '$preview/git-commit {}'";;
	lsf) args['preview']="--preview '$preview/lsf-job {1}'"; filter="awk '{print \$1}'";;
	snip) args['preview']="--preview '$preview/snippet {1}'";;
	tmux)
		#position=bottom
		position=right
		args['height']='--height 100%'
		args['preview']="--preview '$preview/tmux-pane {1}'"
		args['preview-window']="--preview-window $position:50%"
		filter="awk '{print \$1}'"
		;;
	*) echo "WARNING: config '$config' not recognized";;
esac

# Combine options
cmd='fzf'
for name in "${!args[@]}"; do
	((verbosity)) && printf "ARG %-8s : %s\n" "$name" "${args[$name]}"
	cmd+=" ${args[$name]}"
done

# Print and run
((verbosity)) && echo "COMMAND: $cmd"
eval exec $cmd | eval $filter

