#!/usr/bin/env bash
declare -r CURRENT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
declare -r preview="$CURRENT_DIR/preview"

# Uncomment to debug
#verbosity=1

# Get config
config=${1-default}
shift
if ((verbosity)); then
	echo "CONFIG: '$config'"
fi

# Get width/height
width=$(tput cols)
height=$(tput lines)

# Default args
declare -A args
args['multi']="--multi"
# TODO: Dynamically set height based on current height
args['height']='--height 40%'
#args['height']='--height 100%'
args['tiebreak']='--tiebreak=length'
args['reverse']='--reverse'
args['info']='--info inline'
args['keybind']='--bind=ctrl-s:toggle-sort'
args['preview']="--preview '$preview/unknown {}'"
# TODO: Dynamically set preview-window size and position
args['preview-window']="--preview-window right:50%"
args['query']="--query='$@ '"
#args['exact']='--exact'
#args['tiebreak']='--tiebreak=index'
#args['expect']='--expect=ctrl-t,ctrl-v'

# Custom colorscheme
args['color']='--color '
args['color']+='fg:33,bg:233,fg+:39,bg+:236'
args['color']+=',hl:172,hl+:172'
args['color']+=',spinner:166,pointer:166,gutter:236,marker:214'
args['color']+=',prompt:123,info:123'
args['color']+=',border:33,preview-fg:159,preview-bg:235'

# TODO: More previews
	#--preview "'my-fzf-preview-git-diff {}'" \
	#--preview "'git show --color=always --numstat {1}'" \

case "$config" in
	default);;
	dir) args['preview']="--preview '$preview/dir {}'";;
	*) echo "WARNING: config '$config' not recognized";;
esac

# Combine options
cmd='fzf'
for name in "${!args[@]}"; do
	((verbosity)) && printf "ARG %-8s : %s\n" "$name" "${args[$name]}"
	cmd+=" ${args[$name]}"
done

# Print and run
((verbosity)) && echo "COMMAND: $cmd"
eval exec $cmd

