#!/usr/bin/env bash
print-header 'xbar'
cat <<-EOF
- key=shift+k to add a key shortcut
  - Use + to create combinations
  - Example options: CmdOrCtrl, OptionOrAlt, shift, ctrl, super, tab, plus, return, escape, f12, up, down, space
- href=.. to make the item clickable
- color=.. to change the text color. eg. color=red or color=#ff0000
- font=.. to change the text font. eg. font=UbuntuMono-Bold
- size=.. to change the text size. eg. size=12
- shell=.. to make the item run a given script terminal with your script e.g. shell=/Users/user/xbar_Plugins/scripts/nginx.restart.sh if there are spaces in the file path you will need quotes e.g. shell="/Users/user/xbar Plugins/scripts/nginx.restart.sh" (bash is also supported but is deprecated)
- param1= to specify arguments to the script. Additional params like this param2=foo param3=bar
- For example shell="/Users/user/xbar_Plugins/scripts/nginx.restart.sh" param1=--verbose assuming that nginx.restart.sh is executable or shell=/usr/bin/ruby param1=/Users/user/rubyscript.rb param2=arg1 param3=arg2 if script is not executable
- terminal=.. start bash script without opening Terminal. true or false
- refresh=.. to make the item refresh the plugin it belongs to. If the item runs a script, refresh is performed after the script finishes. eg. refresh=true
- dropdown=.. May be set to true or false. If false, the line will only appear and cycle in the status bar but not in the dropdown
- length=.. to truncate the line to the specified number of characters. A … will be added to any truncated strings, as well as a tooltip displaying the full string. eg. length=10
- trim=.. whether to trim leading/trailing whitespace from the title. true or false (defaults to true)
- alternate=true to mark a line as an alternate to the previous one for when the Option key is pressed in the dropdown
- templateImage=.. set an image for this item. The image data must be passed as base64 encoded string and should consist of only black and clear pixels. The alpha channel in the image can be used to adjust the opacity of black content, however. This is the recommended way to set an image for the statusbar. Use a 144 DPI resolution to support Retina displays. The imageformat can be any of the formats supported by Mac OS X
- image=.. set an image for this item. The image data must be passed as base64 encoded string. Use a 144 DPI resolution to support Retina displays. The imageformat can be any of the formats supported by Mac OS X
- emojize=false will disable parsing of github style :mushroom: into 🍄
- ansi=false turns off parsing of ANSI codes.
- disabled=true greyed out the line and disable click
EOF

