#!/usr/bin/env bash
print-header 'BAZEL'

# Variables
cat << 'EOF'

bazel-my-project => <...my-project>     <== Symlink to execRoot
bazel-out => <...bin>                   <== Convenience symlink to outputPath
bazel-bin => <...bin>                   <== Convenience symlink to most recent written bin dir $(BINDIR)
bazel-testlogs => <...testlogs>         <== Convenience symlink to the test logs directory

bazel clean --expunge

EOF

