#!/usr/bin/env bash

# Directories
echo
print-header 'SYMLINK'
cat << 'EOF'
bazel-my-project => <...my-project>     <== execRoot
bazel-out => <...bin>                   <== outputPath
bazel-bin => <...bin>                   <== Most recent written bin dir $(BINDIR)
bazel-testlogs => <...testlogs>         <== Test logs directory
EOF

echo
print-header 'COMMANDS'
cat << 'EOF'
bazel clean --expunge
bazel query '//foo:bar' --output=build
bazel query '//external:*' --output=build
EOF

echo
print-header 'VISIBILITY'
cat << 'EOF'
- //visibility
- //visibility:private
- //foo/bar:__pkg__            Grants access to //foo/bar package
- //foo/bar:__subpackages__    Grants access to //foo/bar and all subpackages

load(":internal_defs.bzl", _helper="helper")
EOF

echo
print-header 'TARGETS'
cat << 'EOF'
# List all targets
bazel query 'kind(".*_test rule", //...)'
EOF

echo
print-header 'PROFILE'
cat << 'EOF'
bazel build --profile="$PWD/profile.gz" <target>
bazel analyze-profile profile.gz
EOF


