#!/usr/bin/env bash
print-header 'Hugo Commands'
cat <<-EOF
hugo new site [path] [flags]
hugo new post posts/POST_NAME.md

# Build to public
hugo
hugo -t <theme>
EOF

echo
print-header 'Hugo Files'
cat <<-EOF
.
├─ config.yaml
├─ content
│  ├─ _index.md
│  ├─ contact.md
│  └─ posts
│     └─ hello-world.md
└─ layouts
   ├─ ├default
   │  ├─ list.html
   │  └─ single.html
   ├─ index.html
   └─ partials
       ├─ footer.html
       └─ header.html
EOF

