#!/usr/bin/env bash
# USAGE: ,help man
print-header 'SECTIONS'
cat <<-EOF
1  Executable programs or shell commands
2  System calls (functions provided by the kernel)
3  Library calls (functions within program libraries)
4  Special files (usually found in /dev)
5  File formats and conventions eg /etc/passwd
6  Games
7  Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7)
8  System administration commands (usually only for root)
9  Kernel routines [Non standard]
EOF
