#!/usr/bin/env bash
declare -r CURRENT_DIR="$(realdir.py "${BASH_SOURCE[0]}")"
page="${!#}"
if [[ "$page" == "$0" ]]; then
	echo "Usage: $(basename "$0") <command>"
	exit
fi
echo -e "MANPAGER=$MANPAGER\n"
echo -e "\033[1;33mPAGE                 - Description\033[0m"
man -f "$page"
echo
export MANPATH="$CURRENT_DIR:$MANPATH"
echo $MANPATH
man "$page"

