#!/usr/bin/env bash
set -e
declare -r CURRENT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# More info here:
# https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash_zsh
#
# The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
# To cd on quit only on ^G, remove the "export" as in:
#     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
# NOTE: NNN_TMPFILE is fixed, should not be modified
export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

# 0 = black
# 1 = red
# 2 = green
# 3 = yellow
# 4 = blue
# 5 = magenta
# 6 = cyan
# 7 = white
export NNN_COLORS='4231'

# Use _ for arbitrary non-background CLI commands
# Use * to skip user confirmation
# Use _| to run a GUI app
# Use -_ to disable directory refresh
NNN_PLUG='g:_git status'
NNN_PLUG+=';b:_nnn-bookmarks*'
NNN_PLUG+=';e:_,env'
#NNN_PLUG+=';h:_cdhome*'
#NNN_PLUG+=';H:_cdhome'
NNN_PLUG+=';P:preview-tui'
#NNN_PLUG+=';a:bookmarks'
NNN_PLUG+=';o:fzopen'
NNN_PLUG+=';p:_nnn-cd-clipboard*'
NNN_PLUG+=';s:_nnn-show-selection'
NNN_PLUG+=';y:-_,clip $nnn*'
NNN_PLUG+=';z:_nnn-zsh*'
export NNN_PLUG

# TODO: Figure out how to get this to work
#open_with="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins/nuke"
#[[ -f "$open_with" ]] && export NNN_OPENER="$open_with"

# Use `less` as opener
export PAGER='less'
export LESS='-Ri'
export NNN_OPENER=less

# Fix ordering
export LC_ALL=C

# Check key collisions
nnn -K

# Open FIFO
export NNN_FIFO="$(mktemp --suffix=-nnn -u)"
(umask 077; mkfifo "$NNN_FIFO")

# Open preview pane
if [[ -e ${TMUX%%,*} ]]; then
	width=$(($(tput cols)-50))
	tmux split-window -dh -l $width nnn-preview $NNN_FIFO
	#tmux split-window \
		#-dh \
		#-e "NNN_FIFO=$NNN_FIFO" \
		#-l $width zsh
fi

# Run nnn
# -c: cli-opener
# -d: detail mode
nnn -c $@

# Clean up FIFO
rm "$NNN_FIFO"

# Print the contents of $NNN_TMPFILE
#if [[ -f  "$NNN_TMPFILE" ]]; then
	#echo "NNN_TMPFILE: $(cat $NNN_TMPFILE)"
	#rm -f $NNN_TMPFILE
#fi

