#!/usr/bin/env bash
set -e
declare -r CURRENT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# Bookmarks
NNN_BMS='h:~'
NNN_BMS+=';b:~/bin'
NNN_BMS+=';d:~/dotfiles'
NNN_BMS+=';l:~/.links'
export NNN_BMS

# More info here:
# https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash_zsh
#
# The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
# To cd on quit only on ^G, remove the "export" as in:
#     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
# NOTE: NNN_TMPFILE is fixed, should not be modified
export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

# 0 = black
# 1 = red
# 2 = green
# 3 = yellow
# 4 = blue
# 5 = magenta
# 6 = cyan
# 7 = white
export NNN_COLORS='4231'

export NNN_PLUG='g:_git status'
export NNN_PLUG+=';l:_less -r $nnn*'

nnn -d $@

# Print the contents of $NNN_TMPFILE
if [[ -f  "$NNN_TMPFILE" ]]; then
	cat $NNN_TMPFILE
	rm -f $NNN_TMPFILE
fi

