#!/usr/bin/env bash
set -e
declare -r CURRENT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# Bookmarks
NNN_BMS='h:~'
NNN_BMS+=';b:~/bin'
NNN_BMS+=';d:~/dotfiles'
NNN_BMS+=';l:~/.links'
export NNN_BMS

# More info here:
# https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash_zsh
#
# The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
# To cd on quit only on ^G, remove the "export" as in:
#     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
# NOTE: NNN_TMPFILE is fixed, should not be modified
export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

# 0 = black
# 1 = red
# 2 = green
# 3 = yellow
# 4 = blue
# 5 = magenta
# 6 = cyan
# 7 = white
export NNN_COLORS='4231'

NNN_PLUG='g:_git status'
NNN_PLUG+=';b:_nnn-bookmarks*'
NNN_PLUG+=';l:_less -r $nnn*'
NNN_PLUG+=';o:fzopen'
NNN_PLUG+=';s:_nnn-show-selection'
#export NNN_PLUG+=';e:_,env'
export  NNN_PLUG

# TODO: Figure out how to get this to work
#open_with="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins/nuke"
#[[ -f "$open_with" ]] && export NNN_OPENER="$open_with"

# I don't like the NNN_OPENER
#export NNN_OPENER=notify-send
export NNN_OPENER=echo

# Fix ordering
export LC_ALL=C

# Check key collisions
nnn -K

# Run nnn
nnn -d $@

# Print the contents of $NNN_TMPFILE
#if [[ -f  "$NNN_TMPFILE" ]]; then
#	cat $NNN_TMPFILE
#	rm -f $NNN_TMPFILE
#fi

