#!/usr/bin/env bash
#obsidian='Obsidian-0.15.9.AppImage'
#check='63d1cf31a1ae9da09c976aa60f907259'

obsidian='Obsidian-1.0.0.AppImage'
check='e65cf93e1beac355de0a6124df06c0dc'

print-run which "$obsidian" || exit $?

# Check Obsidian
obsidian_full="$(which "$obsidian")" || exit $?
echo "$check  $obsidian_full" | md5sum -c - || exit $?

# Log file
log_dir="${XDG_CACHE_HOME:-$HOME/.cache}/obsidian"
log_file="$log_dir/$(date +'%Y%m%d-%H%M%S').log"
mkdir -p "$log_dir"

# Run Obsidian
setsid "$obsidian" &>"$log_file" &
echo "Writing log to: $log_file"

