#!/usr/bin/env bash

function _cat() {
	local file="$1"
	[[ -f "$file" ]] || return
	printf "\e[33;1m==> $file <==\e[0m\n"
	cat "$file"
	echo
}

_cat /etc/os-release
_cat /etc/redhat-release

printf "\e[33;1m\$> uname -r\e[0m\n"
uname -r

echo
printf "\e[33;1m\$> lsb_release -a\e[0m\n"
lsb_release -a

