#!/usr/bin/env bash

function _cat() {
	local file="$1"
	[[ -f "$file" ]] || return
	print-cmd cat "$file"
	cat "$file"
	echo
}

_cat /etc/os-release
_cat /etc/redhat-release

print-cmd uname
uname

echo
print-cmd uname -r
uname -r

echo
print-cmd lsb_release -a
lsb_release -a

echo
print-cmd last reboot
last reboot

