#!/usr/bin/env bash
# USAGE: ,podman-backup
# DESCRIPTION: TODO
id="$1"
name="$(,podman-name "$id")" || exit $?

backup="${name}_backup"
tag="latest"
now="$(date +'%Y%m%d-%H%M%S')"
tar="${backup}-${now}.tar"

print-run podman commit "$name" "$backup:$tag"
print-run podman save -o "$tar" "$backup:$tag"

