#!/usr/bin/env bash
user="$1" && shift
host="$1" && shift
remote_dest="$1" && shift
local_dest="$1" && shift

src="$1"
if [[ -z "$src" ]]; then
	print-usage ,scp '<user>' '<host>' '<remote_dest>' '<local_dest>' '<src/dest>'
	exit 1
fi

if [[ -e "$src" ]]; then
	print-info local to remote
	dest="$user@$host:$remote_dest"
else
	print-info remote to local
	src="$user@$host:$1"
	dest="$local_dest"
fi

cmd_args=()
cmd_args+=(--archive --compress)
cmd_args+=(--progress)
#cmd_args+=(-e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null")
cmd_args+=("$src" "$dest")

print-cmd rsync "${cmd_args[@]}"
yesno || exit 0
rsync "${cmd_args[@]}"

