#!/usr/bin/env bash
# USAGE: ,ts
# DESCRIPTION: Adds a timestamp to each line
ts -i '%.s' | \
awk '
	BEGIN {start = systime()}
	{
		s = systime() - start
		elapsed = sprintf("%02d:%02d:%02d", s/3600, s/60%60, s%60)
		$1 = sprintf("| %s | %06.2f |", elapsed, $1)
		print
	}
'
