#!/usr/bin/env bash
# USAGE: ,ts
# DESCRIPTION: Adds a timestamp to each line
awk '
	BEGIN {start = systime(); prev = start}
	{
		now = systime()
		s = now - start
		diff = now - prev
		elapsed = sprintf("%02d:%02d:%02d", s/3600, s/60%60, s%60)
		printf("| %s | %04d | ", elapsed, diff)
		#printf("| %s | ", elapsed)
		prev = now
		print
	}
'
