#!/usr/bin/env bash
volume-amixer "$1"
#volume-pactl "$1"

# Popup notification for volume
notify-send \
	-t 400 \
	-u normal \
	-h string:x-canonical-private-synchronous:volume \
	"$(,volume-info)"

