#!/usr/bin/env bash
if (type pactl &>/dev/null); then
	volume-pactl "$1"
else
	volume-amixer "$1"
fi

# Popup notification for volume
notify-send \
	-t 400 \
	-u normal \
	-h string:x-canonical-private-synchronous:volume \
	"$(,volume-info)"

