#!/usr/bin/env bash
if ! (type feh &>/dev/null); then
	print-cmd sudo apt install -y feh
	exit 2
fi

wallpaper_dir="$HOME/.config/wallpaper"

function download() {
	url="$1"
	name="${2:-$(basename "$url")}"
	picture="$wallpaper_dir/$name"
	[[ -f "$picture" ]] && return 0
	print-run curl -o "$picture" "$url"
}

mkdir -p "$wallpaper_dir"
download https://stsci-opo.org/STScI-01GA76N47MR44PNWZ4NAYZBKG5.png
download https://stsci-opo.org/STScI-01GA77J0WFC48EQAWEH5AWF1FQ.png
download https://stsci-opo.org/STScI-01G8JXRG3DGMM2R8HS37YRG531.png
download https://stsci-opo.org/STScI-01G77Q9ABGAEX4CDSKBSDC3FWN.jpg
download https://stsci-opo.org/STScI-01G77PKYA4T05YKJ3EDQ36NZCX.png
download https://stsci-opo.org/STScI-01G7DA7WM13DBQNKV4EHRFCCJ7.png
download https://stsci-opo.org/STScI-01G70BN48JR6M4ZTW3642X2D2H.png
download https://stsci-opo.org/STScI-01G7DCYVZ899DGSY684E801B2Y.png
download https://stsci-opo.org/STScI-01G1Q6CSGZG0K9MK6JXXR9120C.png
download https://stsci-opo.org/STScI-01FMN22BJXHTZ1HKWMFR8DWFAJ.jpg
download https://stsci-opo.org/STScI-01FJHQFKZXM0ANBAGZSTAP9XEK.png
download https://stsci-opo.org/STScI-01F0SV55ZF29KH11ZWNRD89FNA.png
download https://stsci-opo.org/STScI-01EVSSW5Z175NMH8C4NW7DX9ZN.png
download https://stsci-opo.org/STScI-01EVST6Z7WR1MY3GF14FBC5B94.png
download https://stsci-opo.org/STScI-01EVST6T6BGPVME5V1WK6EWZ44.png
download https://stsci-opo.org/STScI-01EVST6MF67AYSWCXP14JZ97DB.png
download https://stsci-opo.org/STScI-01EVSTFG11Z011TWQSTZ4ASBBW.png
download https://stsci-opo.org/STScI-01EVSV6NM7QVX4ATNCJT6Z28T1.jpg
download https://stsci-opo.org/STScI-01EVSV6RAD2XZGBNKD66KS2D51.jpg
download https://stsci-opo.org/STScI-01EVSWN16DT10GWBKNZ9BZE8MA.jpg
download https://stsci-opo.org/STScI-01EVSYW3SGEZ7ZXRQPFCS3YY5R.jpg
download https://stsci-opo.org/STScI-01FN9CQM93S12ZNFSXGFZEYWG8.png
download https://stsci-opo.org/STScI-01EVT0Y111TWTRZ1MF817NR6WW.png
download https://stsci-opo.org/STScI-01G0D373ZZQJCSMG1TTYRGXD6R.png
download https://stsci-opo.org/STScI-01EVT0DBXZB9MA4TJ74VQE58NZ.png
download https://stsci-opo.org/STScI-01EVT0ER929574VHS93D38CK19.png
download https://stsci-opo.org/STScI-01EVT0E6AVV39FZ2S7GTBYDMRY.jpg
download https://stsci-opo.org/STScI-01EVSZFRKQJGJ166919T712YDF.png
download https://stsci-opo.org/STScI-01EVT0DJKW6J247K7M6FZRCMQS.png
download https://stsci-opo.org/STScI-01GF42D0KV99R21EAD1RAZ3JB7.png

# https://wiki.archlinux.org/title/feh
# https://www.reddit.com/r/i3wm/comments/w7u6x9/comment/ihln1xk/
print-run feh --recursive --randomize --bg-fill "$wallpaper_dir"

