#!/usr/bin/env ruby
# vim: ft=ruby noet ts=4 sw=0 sts

def print_response(response)
	main = response.match(/<main>\n(.*)^<\/main>/m)[1]
	result = main.gsub(/<p>/,"\n").gsub(/<.*?>/m,'').split("\n").join(' ').gsub(/\s+/,' ').strip

	right = "That's the right answer!"
	wrong = "That's not the right answer."
	early = "You gave an answer too recently;"

	reset = "\e[0m"
	bold_red = "\e[31;1m"
	bold_green = "\e[32;1m"
	bold_yellow = "\e[33;1m"
	bold_cyan = "\e[34;1m"

	result.gsub!(/\[.+?\]/, "#{bold_cyan}\\0#{reset}")
	result.gsub!(right, "#{bold_green}#{right}#{reset}")
	result.gsub!(wrong, "#{bold_red}#{wrong}#{reset}")
	result.gsub!(early, "#{bold_yellow}#{early}#{reset}")
	puts result
end

ARGV.each do |file|
	print_response(File.read(file))
end

