#!/usr/bin/env bash
gcc="$(which aarch64-linux-gnu-gcc 2>/dev/null)"
if [[ -z "$gcc" ]]; then
	print-run sudo apt install -y gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
	gcc="$(which aarch64-linux-gnu-gcc 2>/dev/null)"
fi

usage="USAGE: arm <cmd> [args]"
gcc_path="$(dirname "$gcc")"

# Check usage
if [[ -z "$1" ]]; then
	echo "$usage"
	echo
	ls -hl --color=auto "$gcc_path/"aarch64-linux-gnu-*
	exit 2
fi

# Get command
gcc_cmd="$1" && shift
case "$gcc_cmd" in
	elf)
		# TODO: Implement this to check if it's an ARM ELF
		echo "Not implemented yet."
		exit 2
		;;

	disass)
		elf="$1" && shift
		# TODO: Check with `arm elf` command
		exec aarch64-linux-gnu-objdump -axdS "$elf" > "$elf.disass"
		;;

	*)
		gcc_cmd="aarch64-linux-gnu-$gcc_cmd"
		if !(type "$gcc_cmd" &>/dev/null); then
			echo "Command '$gcc_cmd' not found"
			exit 2
		fi
		arm_cmd=("$gcc_cmd" "${@}")
		;;
esac

# Run
print-cmd "${arm_cmd[@]}"
exec "${arm_cmd[@]}"

