#!/usr/bin/env bash
# Add the following to your .bashrc:
# ---
# if command -v bash-prompt &>/dev/null; then
# 	PROMPT_COMMAND='PS1="$(RETVAL=$? bash-prompt)"'
# 	export start_ms
# 	function preexec() {
# 		[[ -n "$COMP_LINE" ]] && return
# 		[[ "$BASH_COMMAND" == "$PROMPT_COMMAND" ]] && return
# 		printf "\x1b[38;5;8m[$(date +%T)] Started\e[0m\n"
# 		start_ms="$(date +'%s%3N')"
# 	}
# 	trap 'preexec' DEBUG
# fi

current_ms="$(date +'%s%3N')"

#dir=${PWD%/*/*}
#dir2=${PWD#$dir/}
permission=$(stat -c %a .)
reset="\[\e[0m\]"
red='\[\e[1;31m\]'
green='\[\e[1;32m\]'
yellow='\[\e[1;93m\]'
blue='\[\e[1;34m\]'
magenta='\[\e[1;35m\]'
cyan='\[\e[1;36m\]'
white='\[\e[1;37m\]'

# Get exit code of last command
((RETVAL)) && echo "\e[31m(exited $RETVAL)\e[0m"

# Get execution time
if ((start_ms)); then
	printf "\x1b[38;5;8m[$(date +%T)] Finished in "

	# Print seconds
	total_ms=$((current_ms - start_ms))
	ms=$((total_ms % 1000))
	total_s=$((total_ms / 1000))
	printf "%d.%03ds" "$total_s" "$ms"

	# Print hours
	if (( total_s >= 3600 )); then
		h="$(($total_s/3600))"
		printf " (%d.%02d hours)" "$h" "$(((total_s%3600)*100/3600))"
	fi
	printf "\e[0m\n"
fi

# Prompt
prompt=''


# ==============================================================================
# USERNAME
# ==============================================================================
#prompt+="$blue\u"
prompt+="${blue}todd"


# ==============================================================================
# HOST
# ==============================================================================
if [[ ! -e ${TMUX%%,*} ]]; then
	[[ -n $LSB_BATCH_JID ]] && lsf=1 || lsf=0
	[[ $lsf == 1 ]] && prompt+=":$yellow$LSB_BATCH_JID$blue" || prompt+="@\h"
fi


# ==============================================================================
# DIRECTORY
# ==============================================================================
# Check PWD for user
pwd | grep -q $(whoami) && prompt+=" $green\W " || prompt+=" $yellow\W "

# Directory permissions
p1="${permission:(-3):1}"
p2="${permission:(-2):1}"
p3="${permission:(-1):1}"
[[ $(whoami) == $(stat -c %U .) ]] && prompt+="$green$p1" || prompt+="$red$p1"
groups | grep -q $(stat -c %G .)   && prompt+="$green$p2" || prompt+="$red$p2"
prompt+="$green$p3"


# ==============================================================================
# END
# ==============================================================================
# Check last command
#if [[ -n "$RETVAL" ]]; then
	#[[ $RETVAL == 0 ]] && prompt+=" $green:)" || prompt+=" $red:("
#fi
prompt_char='$'
prompt_char='»'
#prompt_char='≫'
#prompt_char='⪢'
#prompt_char='▶'
#prompt+=" $cyan$prompt_char$reset "
prompt+=" $yellow$prompt_char$reset "

echo "$prompt"

