#!/usr/bin/env bash

hl_args=()
hl_args+=('^Job Name' '^Job' User Project Status Queue)
hl_args+=('Interactive mode' Command 'Submitted from host')
hl_args+=(Started Allocated 'Resource usage collected')
hl_args+=('^Output File' '^Error File')
hl_args+=('^Execution Home' '^Execution CWD' CWD)
hl_args+=(RUNLIMIT MEMLIMIT 'MEMORY USAGE' 'CPU USAGE')
hl_args+=('SCHEDULING PARAMETERS' 'RESOURCE REQUIREMENT DETAILS')
#
exec bjobs -UF "$@" \
	| awk 'BEGIN{RS=", +|;?\n"} {$1=$1;print}' \
	| hl "${hl_args[@]}"

