#!/usr/bin/env bash

hl_args=()

hl_args+=(--yellow '^Job <.*>' '^Status <.*>')
hl_args+=('^Job <.*>')
hl_args+=('^Status <.*>')
hl_args+=('^System APS priority <.*>')

hl_args+=(--green '^Job <.*>' '^Status <.*>')
hl_args+=('Submitted from host')
hl_args+=('Started')
hl_args+=('Done successfully\.')

hl_args+=(--red)
hl_args+=('Exited')

hl_args+=(--blue)
hl_args+=('^Job Name' '^Job Description' '^Job Group' '^Job Priority')
hl_args+=('User' 'Project' 'Application' 'Queue' 'Command')
hl_args+=('Interactive mode')
hl_args+=('Allocated' 'Resource usage collected')
hl_args+=('^Output File' '^Error File')
hl_args+=('^Execution Home' '^Execution CWD' 'CWD')
hl_args+=('Requested Resources' 'PENDING REASONS')
hl_args+=(RUNLIMIT ESTIMATED_RUNTIME MEMLIMIT 'MEMORY USAGE' 'CPU USAGE')
hl_args+=('SCHEDULING PARAMETERS' 'RESOURCE REQUIREMENT DETAILS')
#
exec bjobs -UF "$@" \
	| awk 'BEGIN{RS=", +|;?\n"} {$1=$1;print}' \
	| hl "${hl_args[@]}"

