#!/usr/bin/env python3
from sys import argv, exit

argv.pop(0)

number = int(argv.pop(0), 16)

# Get fields
fields = []
widths = []
for field in argv:
    name, value = field.split(':')
    fields.append(name)
    widths.append(int(value))

# Start with LSB
fields.reverse()
widths.reverse()

total_width = 0
message = []
for i in range(len(fields)):
    field = fields[i]
    width = widths[i]
    bits = 2**width-1
    value = ((bits << total_width) & number) >> total_width
    message.append(f'{field}: {bin(value)}')
    total_width += width

# Print
message.reverse()
print("\n".join(message))

