#!/usr/bin/env bash
set -e

# TODO: Cleaner way to handle colors: https://github.com/SinaKhalili/mecho/blob/main/mecho.sh

function fg_color() {
	case "$1" in
		black)   echo 30;;
		red)     echo 31;;
		green)   echo 32;;
		yellow)  echo 33;;
		blue)    echo 34;;
		magenta) echo 35;;
		cyan)    echo 36;;
		white)   echo 37;;
	esac
}

function bg_color() {
	case "$1" in
		black)   echo 40;;
		red)     echo 41;;
		green)   echo 42;;
		yellow)  echo 43;;
		blue)    echo 44;;
		magenta) echo 45;;
		cyan)    echo 46;;
		white)   echo 47;;
	esac
}

code=''
newline=$'\n'
parse=1
while ((parse)); do
	case "$1" in
		--fg) code+=";$(fg_color "$2")"; shift 2;;
		--bg) code+=";$(bg_color "$2")"; shift 2;;
		--bold) code+=";1"; shift;;
		--italic) code+=";3"; shift;;
		--underline) code+=";4"; shift;;
		--blink) code+=";5"; shift;;
		-n) newline=''; shift;;
		# TODO: Implement more escape codes, e.g. underline
		# https://en.wikipedia.org/wiki/ANSI_escape_code
		*) parse=0;;
	esac
done

printf "\e[${code}m%s\e[0m$newline" "$(echo "$@")"

