#!/usr/bin/env ruby
# vim: ft=ruby

# TODO: Add Chi-Squared test
# https://stackoverflow.com/questions/11725115/p-value-from-chi-sq-test-statistic-in-python
# >>> 1 - stats.chi2.cdf(3.84, 1)
0# .050043521248705147


# ==============================================================================
# EXAMPLE
# ==============================================================================
# $> chi 21.333 29 24 22 19 21 18 19 20 23 18 20 23
# 5.0938296535883385


# ==============================================================================
# INPUTS
# ==============================================================================
expected = ARGV.shift.to_f
observed_values = ARGV.map(&:to_f)


# ==============================================================================
# CALCULATE
# ==============================================================================
chi_squared = 0.0
observed_values.each do |observed|
	calc = ((observed - expected) ** 2) / expected
	chi_squared += calc
	next
	puts '-'
	p observed
	p calc
end

p chi_squared

