#!/usr/bin/env bash
# Copy text using OSC 52 escape sequence.

# Example:
# https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/etc/osc52.sh

# Encode string from stdin
to_copy="$(base64 | tr -d '\n')"

# Run OSC 52 escape sequence
print-dcs "52;c;$to_copy"

