#!/usr/bin/env bash
declare -r dir=${1-$(readlink -f $PWD)}
tmpfile=$(TMPDIR=$dir mktemp)

# Clean up temp file
function finish() {
	local RETVAL=$?
	rm -f $tmpfile
}
eval trap "'finish $0 $@'" EXIT

# Print stats
print-run df -Ph "$dir"
print-run dd if=/dev/random of="$tmpfile" bs=32768 count=10000

