#!/usr/bin/env bash
dir="${1:-.}"
depth="${2:-3}"
[[ -d "$dir" ]] || exit 1

base="$(basename "$dir")"
if [[ "$base" == '.' ]] && [[ "$dir" != . ]]; then
	exit 1
elif [[ "$base" == '..' ]]; then
	exit 1
fi

result="$(du --max-depth=0 "$dir" 2>/dev/null)" || exit 1
read -r size _ <<<"$result"
((size=size/1024))


case "$base" in
	.git) last=1;;
	work) last=1;;
	logs) last=1;;
	test.outputs) last=1;;
	*) last=0;;
esac

if ((last)); then
	printf '%-10s %s\n' "$size" "$dir"
	exit 0
fi

((size<100)) && exit 1

if ((depth)); then
	((depth--))
	for d in "$dir"/* "$dir"/.*; do
		"$0" "$d" "$depth"
	done
fi

printf '%-10s %s\n' "$size" "$dir"
exit 0

