#!/usr/bin/env bash

exec &> >(tee du.txt)

du 2>/dev/null | while read -r size dir; do
	size_mb="$((size/1024))"
	((size_mb<100)) && continue

	case "$dir" in
		*/.git/*)      continue;;
		*/.venv/*)     continue;;
		*/venv/*)      continue;;
		*/logs/*)      continue;;
		*/lib/*)       continue;;
		*/external/*)  continue;;
		*/execroot/*)  continue;;
		*.zCui.work/*) continue;;
	esac

	printf '%8s  %s\n' "$size_mb" "$dir"
	[[ "$(dirname "$dir")" == '.' ]] && echo
	[[ -d "$dir/.git" ]] && echo
done

