#!/usr/bin/env bash

du 2>/dev/null | while read -r size dir; do
	size_mb="$((size/1024))"
	((size_mb<100)) && continue
	[[ "$dir" == */.git/* ]] && continue
	[[ "$dir" == */.venv/* ]] && continue
	[[ "$dir" == */logs/* ]] && continue
	[[ "$dir" == */lib/* ]] && continue

	[[ "$dir" == *.zCui.work/* ]] && continue

	[[ "$dir" == */external/* ]] && continue
	[[ "$dir" == */execroot/* ]] && continue

	printf '%-10s %s\n' "$size_mb" "$dir"
done

