#!/usr/bin/env bash

du 2>/dev/null | while read -r size dir; do
	size_mb="$((size/1024))"
	((size_mb<100)) && continue

	case "$dir" in
		*/.git/*)      continue;;
		*/.venv/*)     continue;;
		*/logs/*)      continue;;
		*/lib/*)       continue;;
		*/external/*)  continue;;
		*/execroot/*)  continue;;
		*.zCui.work/*) continue;;
	esac

	printf '%-10s %s\n' "$size_mb" "$dir"
done

