#!/usr/bin/env bash
if [[ "$#" -eq 0 ]]; then
	find_args=(.)
elif [[ "$#" -eq 1 ]]; then
	name="$1"
	find_args=(. -iname "*$name*")
else
	# TODO: Support more names
	path="$1"
	name="$2"
	find_args=("$path" -iname "*$name*")
fi
exec find "${find_args[@]}" 2>/dev/null
