#!/usr/bin/env bash
if [[ "$#" -eq 0 ]]; then
	exec find . -type d
elif [[ "$#" -eq 1 ]]; then
	name="$1"
	exec find . -type d -name "*$name*"
else
	# TODO: Support more names
	path="$1"
	name="$2"
	exec find "$path" -type d -name "*$name*"
fi

