#!/usr/bin/env bash
# USAGE: find <args> | find2tree
# https://stackoverflow.com/questions/54228819/tree-command-not-found
if (type diagon &>/dev/null); then
	sed -e "s:[^/]*/:  :g" | diagon Tree --style='unicode 1'
else
	sed -e 's:[^/]*/:|____:g;s:____|: |:g'
fi
