#!/usr/bin/env bash
# USAGE: git ls-rebase
# DESCRIPTION: List all of the commits
git has-unstaged || { print-error "You have unstaged changes, please commit or stash them."; exit 1; }
GIT_SEQUENCE_EDITOR="grep ^pick" git rebase -i 2>/dev/null
