#!/usr/bin/env bash
# USAGE: git ls-rebase
# DESCRIPTION: List all of the CLs
commit="${1?commit not set}"
sed_expr="s/^pick $commit/drop $commit/"

print-info "Running 'git rebase -i'"
git ls-rebase | sed "$sed_expr"
echo
GIT_SEQUENCE_EDITOR="sed -i -e '$sed_expr'" git rebase -i

