#!/usr/bin/env bash
# DESCRIPTION: Set upstream branch
#branch_name="$(git branch-name)"
branch_name="main"
upstream="${1:-origin/$branch_name}"
print-run git remote -v
yesno "Set upstream to '$upstream'?" || exit $?
print-run git branch --set-upstream-to="$upstream"
print-run git remote -v

