#!/usr/bin/env bash
# DESCRIPTION: List local/unpushed commits
if [[ -z "$1" ]]; then
	current_branch="$(git rev-parse --abbrev-ref HEAD)"
	remote_branch="origin/$current_branch"
else
	remote_branch="$1"
fi
print-cmd "git ls $remote_branch..HEAD"
git ls "$remote_branch..HEAD"
