#!/usr/bin/env bash
branch="$(git rev-parse --abbrev-ref HEAD)"
if [[ -z "$1" ]]; then
	remote_branch="$branch"
else
	remote_branch="$1"
fi
echo "source: '$branch'"

destination="refs/for/$remote_branch"
if [[ "$branch" == 'meta/config' ]]; then
	destination="refs/for/refs/$branch"
fi
echo "destination '$destination'"
echo
print-cmd "git push origin $branch:$destination"
exec git push origin "$branch:$destination"

