#!/usr/bin/env bash
repo="${1?}" && shift
dir="${1:-$repo}" && shift
print-run git clone "https://github.com/toddky/$repo" "$dir" || exit $?
print-cmd cd "$dir"
cd "$dir"
print-run git remote add toddky "git@github.com:toddky/$repo"
print-run git remote add toddyamakawa "git@github.com:toddyamakawa/$repo"
