#!/usr/bin/env bash
fetch_url="$(git config --get remote.origin.url)"

if ! [[ "$fetch_url" =~ ^ssh:// ]]; then
	echo "ERROR: Unable to parse URL '$fetch_url'" 1>&2
	exit 2
fi

echo "fetch_url: $fetch_url" 1>&2
info="$(echo "$fetch_url" | sed -e 's/^ssh:\/\///')"
read -r host port project <<< "$(echo "$info" | tr ':' ' '| sed -e 's:/: :')"
echo "host: $host" 1>&2
echo "port: $port" 1>&2
echo "project: $project" 1>&2

#printf "\e[33;1m$> %s\e[0m\n" "$(tr $'\n' ' ' <<< "ssh -xp$port $USER@$host -- gerrit $@")"
print-cmd "ssh -xp$port $USER@$host -- gerrit $@" 1>&2
exec ssh "-xp$port" "$USER@$host" -- gerrit "$(printf '%q ' "$@")"

