#!/usr/bin/env bash
set -e
print-run git clone "git@github.com:toddky/qmk_firmware" qmk
echo

print-cmd cd qmk
cd qmk
print-run git remote add upstream     "git@github.com:qmk/qmk_firmware"
print-run git remote add toddyamakawa "git@github.com:toddyamakawa/qmk_firmware"
print-run git remote add toddky       "git@github.com:toddky/qmk_firmware"

