#!/usr/bin/env bash
IFS=$'\n'
for git_file in $(git grep -l TODO); do
	for blame_line in $(git blame "$git_file" | grep TODO); do
		#echo "$blame_line"
		date="$(echo "$blame_line" | sed -n 's/.*\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\).*/\1/p')"
		#line_number="$(echo "$blame_line" | cut -d ')' -f 1 | awk '{print $NF}')"
		line_number="$(echo "$blame_line" | sed -n 's/.* \([0-9]\+\)).*/\1/p')"
		todo="$(echo "$blame_line" | sed -n 's/.*TODO:\?\s*//p')"
		printf '%s | %3d | %-20s | %s\n' "$date" "$line_number" "$git_file" "$todo"
	done
done

