#!/usr/bin/env bash
# TODO: Implement this
# https://github.com/mattorb/dotfiles/blob/f8ab099f8105e4700a713b75ba32df3ac723d485/git/.gitaliases#L102

# https://junegunn.kr/2015/03/browsing-git-commits-with-fzf

