#!/usr/bin/env bash
# DESCRIPTION: Commit staged changes and edit commit message
git staged || exit $?

staged="$(git ls-staged)"
print-cmd git commit -m "$staged"
git commit -m "$staged" || exit $?

print-cmd git amend
git amend || exit $?
