#!/usr/bin/env bash
# DESCRIPTION: Commit staged changes and edit commit message
git staged || exit $?

staged="$(git ls-staged)"
print-cmd git commit -m "$staged"
cmd git commit -m "$staged"

print-cmd git amend
git amend
