#!/usr/bin/env bash
USAGE='USAGE: gitc <dir> <command>'
dir="$1" && shift
if [[ -z "$dir" ]]; then
	printf "$USAGE\n" 1>&2
	exit 2
fi
if [[ -z "$@" ]]; then
	printf "$USAGE\n" 1>&2
	exit 2
fi
cd "$dir" || exit $?
exec git "$@"
