#!/usr/bin/env bash
USAGE='USAGE: gitc <dir> [command]'
dir="$1" && shift
if [[ -z "$dir" ]]; then
	printf "$USAGE\n" 1>&2
	exit 2
fi
git_args=("$@")
if [[ -z "$@" ]]; then
	git_args=(status)
fi
cd "$dir" || exit $?
exec git safe "${git_args[@]}"
