#!/usr/bin/env python3
# USAGE: gitlab-ls-mr
# DESCRIPTION: TODO

from python_lib import gitlab

import json
import os
import requests
import sys

ACCESS_TOKEN = gitlab.get_key()
GITLAB_URL = gitlab.get_url()

url = f"{GITLAB_URL}/api/v4/merge_requests?state=opened&scope=assigned_to_me"
headers = {
    'Private-Token': ACCESS_TOKEN
}
response = requests.get(url, headers=headers)

if response.status_code != 200:
    print(f"Failed to retrieve merge requests: {response.status_code}", file=sys.stderr)
    sys.exit(1)

columns = ['ID', 'Proj', 'Title', 'Assignee', 'Branches', 'URL']
print(','.join(columns))

merge_requests = response.json()
for mr in merge_requests:
    mr_id        = mr['iid']
    project_id   = mr['project_id']
    state        = mr['state']
    assignee     = mr['assignee']['name']
    title        = mr['title']
    source      = mr['source_branch']
    target      = mr['target_branch']
    web_url      = mr['web_url']
    #print(json.dumps(mr, indent=2)); sys.exit(0)
    print(f"{mr_id},{project_id},{title},{assignee},{source}->{target},{web_url}")

