#!/usr/bin/env bash

print-run git fetch
if ! (git behind); then
	echo
	echo "No new commits"
	exit
fi

print-run git diff-index --quiet --exit-code --ignore-submodules HEAD
local_changes=$?

if ((local_changes)); then
	print-run git stash
	print-run git rebase || exit $?
	print-run git stash pop --quiet
	print-run git unstage-all
else
	print-run git rebase
fi

