#!/usr/bin/env bash
set -e

printf "\e[33;1m$> %s\e[0m\n" 'git stash'
git stash
printf "(exited $?)\n\n"

printf "\e[33;1m$> %s\e[0m\n" 'git pull --rebase'
git pull --rebase
printf "(exited $?)\n\n"

printf "\e[33;1m$> %s\e[0m\n" 'git stash pop --quiet'
git stash pop --quiet
printf "(exited $?)\n\n"

printf "\e[33;1m$> %s\e[0m\n" 'git unstage-all'
git unstage-all
printf "(exited $?)\n\n"

