#!/usr/bin/env bash
set -e

print-run git fetch
if ! (git behind); then
	echo
	echo "No new commits"
	exit
fi

print-run git stash
print-run git pull --rebase
print-run git stash pop --quiet
print-run git unstage-all

