#!/bin/bash

ESC="$(         echo -e "\033")"
RESET="$(       echo -e "\033[0m")"
BOLD_RED="$(    echo -e "\033[31;1m")"
BOLD_GREEN="$(  echo -e "\033[32;1m")"
BOLD_YELLOW="$( echo -e "\033[33;1m")"
BOLD_BLUE="$(   echo -e "\033[34;1m")"
BOLD_MAGENTA="$(echo -e "\033[35;1m")"
BOLD_CYAN="$(   echo -e "\033[36;1m")"

RED="$(    echo -e "\033[31m")"
GREEN="$(  echo -e "\033[32m")"
YELLOW="$( echo -e "\033[33m")"
BLUE="$(   echo -e "\033[34m")"
MAGENTA="$(echo -e "\033[35m")"
CYAN="$(   echo -e "\033[36m")"

BOLD_UNDERLINE_CYAN="$(echo -e "\033[36;4;1m")"
BOLD="$(echo -e "\033[1m")"

WIDTH="$(tput cols)"
BAR="$(printf "%${WIDTH}s" ' ' | sed 's/ /─/g')"
#BAR='────────────────────────────────────────────────────────────────────────────────'

color="$BOLD_YELLOW"

sed_args=(-u)
for arg in "$@"; do
	case "$arg" in

		--red)            pre="$BOLD_RED"    ; post="$RESET"; continue;;
		--green)          pre="$BOLD_GREEN"  ; post="$RESET"; continue;;
		--yellow)         pre="$BOLD_YELLOW" ; post="$RESET"; continue;;
		--blue)           pre="$BOLD_BLUE"   ; post="$RESET"; continue;;
		--magenta)        pre="$BOLD_MAGENTA"; post="$RESET"; continue;;
		--cyan)           pre="$BOLD_CYAN"   ; post="$RESET"; continue;;

		--normal-red)     pre="$RED"         ; post="$RESET"; continue;;
		--normal-green)   pre="$GREEN"       ; post="$RESET"; continue;;
		--normal-yellow)  pre="$YELLOW"      ; post="$RESET"; continue;;
		--normal-blue)    pre="$BLUE"        ; post="$RESET"; continue;;
		--normal-magenta) pre="$MAGENTA"     ; post="$RESET"; continue;;
		--normal-cyan)    pre="$CYAN"        ; post="$RESET"; continue;;

		--header)         pre="$pre$BAR\n"   ; post="\n$BAR$post"; continue;;
	esac
	sed_args+=(-e "s|\($arg\)|$pre\\1$post|g")
done

exec sed "${sed_args[@]}"

