#!/bin/bash

ESC="$(         echo -e "\033")"
RESET="$(       echo -e "\033[0m")"
BOLD_RED="$(    echo -e "\033[31;1m")"
BOLD_GREEN="$(  echo -e "\033[32;1m")"
BOLD_YELLOW="$( echo -e "\033[33;1m")"
BOLD_BLUE="$(   echo -e "\033[34;1m")"
BOLD_MAGENTA="$(echo -e "\033[35;1m")"
BOLD_CYAN="$(   echo -e "\033[36;1m")"

RED="$(    echo -e "\033[31m")"
GREEN="$(  echo -e "\033[32m")"
YELLOW="$( echo -e "\033[33m")"
BLUE="$(   echo -e "\033[34m")"
MAGENTA="$(echo -e "\033[35m")"
CYAN="$(   echo -e "\033[36m")"

BOLD_UNDERLINE_CYAN="$(echo -e "\033[36;4;1m")"
BOLD="$(echo -e "\033[1m")"

BAR='────────────────────────────────────────────────────────────────────────────────'

color="$BOLD_YELLOW"

sed_args=(-u)
for arg in "$@"; do
	case "$arg" in
		--red)     color="$BOLD_RED"     && continue;;
		--green)   color="$BOLD_GREEN"   && continue;;
		--yellow)  color="$BOLD_YELLOW"  && continue;;
		--blue)    color="$BOLD_BLUE"    && continue;;
		--magenta) color="$BOLD_MAGENTA" && continue;;
		--cyan)    color="$BOLD_CYAN"    && continue;;

		--normal-red)     color="$RED"     && continue;;
		--normal-green)   color="$GREEN"   && continue;;
		--normal-yellow)  color="$YELLOW"  && continue;;
		--normal-blue)    color="$BLUE"    && continue;;
		--normal-magenta) color="$MAGENTA" && continue;;
		--normal-cyan)    color="$CYAN"    && continue;;
	esac
	sed_args+=(-e "s|\($arg\)|$color\\1$RESET|g")
done

sed "${sed_args[@]}"

