#!/usr/bin/env bash
#info="$(xprop | sed -n 's/WM_CLASS.*, *//p')"
info="$(xprop | grep WM)"

tempfile="$(mktemp)"
function finish {
	rm -rf "$tempfile"
}
trap finish EXIT

echo "$info" > "$tempfile"
xless "$tempfile" & sleep 1

