#!/usr/bin/env python3

import json
import subprocess

# Get tree
output = subprocess.check_output(['i3-msg', '-t', 'get_tree'])
tree = json.loads(output)

# Check if current window is in a tabbed layout
def is_tabbed(tree, parent_count = 0):
    if tree['focused']: return True

    layout = tree['layout']
    count = len(tree['nodes'])

    for node in tree['nodes']:
        if is_tabbed(node, count):
            #print(f"{node['name']} <{layout}>")
            #print(f"{node['name']} <{layout},{parent_count}> {count}")
            if layout == 'tabbed' and parent_count != 1:
                exit(0)
            else:
                exit(1)

    return False

is_tabbed(tree)
exit(1)

