#!/usr/bin/env bash
# https://www.reddit.com/r/i3wm/comments/uv9pyg/making_the_modshifte_exit_menu_more_useful/
# Exit menu
exec i3-nagbar -f "pango:Terminus 12" \
  -m "Exit i3? This will end your current X session." \
  -B "Exit now" "i3-msg exit" \
  -B "Suspend" "systemctl suspend && pkill i3-nagbar" \
  -B "Reboot" "systemctl reboot" \
  -B "Power off" "systemctl poweroff"

