#!/usr/bin/env bash

if command -v gnome-terminal &> /dev/null; then
	# Fixes this error:
	# Error creating terminal: Failed to get screen from object path /org/gnome/Terminal/screen/...
	export GNOME_TERMINAL_SCREEN=''

	exec gnome-terminal --hide-menubar
fi

i3-nagbar -m 'i3-term could not find a terminal emulator. Please fix it.'
exit 2

