#!/usr/bin/env python3
# USAGE: jira-new-issue.py --email <email> --project <project> --summary <summary> --description <description> --type <type> --parent <parent>
# DESCRIPTION: Create a new JIRA issue

import json
import os
import requests
import sys

from python_lib import myjira

import argparse

parser = argparse.ArgumentParser(description='Create a new JIRA issue')
parser.add_argument('--email'      , required=True, help='Email address of the assignee')
parser.add_argument('--project'    , required=True, help='Project key')
parser.add_argument('--summary'    , required=True, help='Issue summary')
parser.add_argument('--description', required=True, help='Issue description')
parser.add_argument('--type'       , required=True, help='Issue type')
parser.add_argument('--parent'     ,                help='Parent issue key')
args = parser.parse_args()

jira = myjira.get_client(args.email)

# Create a new issue
issue_dict = {
    'project': {'key': args.project},
    'summary': args.summary,
    'description': args.description,
    'issuetype': {'name': args.type},
}
if args.parent:
    issue_dict['parent'] = {'key': args.parent}
new_issue = jira.create_issue(fields=issue_dict)

# Assign the issue to yourself
jira.assign_issue(new_issue, args.email)
print(f"Created {new_issue.key}")

