#!/usr/bin/env bash
# Check /tmp for LSF jobs
host="$(hostname -s)"
bjobs -m "$host" -u all

echo
bjobs -m "$host" -u all | \
	sed -n 's/^\([0-9]\+\) .*/\1/p' | \
	sort | uniq | sort | \
	xargs -I {} -n 1 sh -c 'ls -ld /tmp/*{}*.tmpdir'

