#!/usr/bin/env bash
# ==============================================================================
# README
# ==============================================================================
# I am the original author of nnn's preview-tui script:
# https://github.com/jarun/nnn/blob/master/plugins/preview-tui
#
# I do not use nnn's preview-tui plugin because I prefer to have more control
# with my own custom preview scripts.


# ==============================================================================
# SETUP
# ==============================================================================
declare -r CURRENT_DIR="$(dirname "$(realpath.py "${BASH_SOURCE[0]}")")"
declare -r preview="$CURRENT_DIR/preview_scripts"

# Check FIFO
export NNN_FIFO=${NNN_FIFO:-$1}
if [[ ! -r "$NNN_FIFO" ]]; then
	echo "Unable to open \$NNN_FIFO='$NNN_FIFO'"
	exit 2
fi

# Close tmux pane on exit
if [[ -n "$TMUX_PANE" ]]; then
	#tmux set-option -t $TMUX_PANE remain-on-exit on
	tmux set-option -t "$TMUX_PANE" remain-on-exit off
fi

# Open pager
tmpdir="$(mktemp -d)"
function fifo_pager() {
	cmd="$1" && shift

	# Create FIFO
	tmpfifo="$tmpdir/nnn-preview.$$.fifo"
	mkfifo "$tmpfifo" || return

	# Open FIFO with pager
	${PAGER:-less -R} < "$tmpfifo" &
	(
		exec > "$tmpfifo"
		"$cmd" "$@" &
	)
	rm "$tmpfifo"
}

# REVISIT: Use $NNN_PWD for something
#NNN_PWD=$PWD


# ==============================================================================
# PREVIEW
# ==============================================================================
# Read selection from $NNN_FIFO
while read -r selection; do
	# REVISIT: Use this for something
	#basedir="$(dirname "$selection")"
	#if [[ "$basedir" != "$NNN_PWD" ]]; then
		#NNN_PWD="$basedir"
	#fi

	# Kill background jobs
	kill %- %+ 2>/dev/null && wait %- %+ 2>/dev/null
	clear

	# Handle directory
	if [[ -d "$selection" ]]; then
		cd "$selection"
		fifo_pager $preview/dir "$selection"
		continue
	fi

	# Handle file
	if [[ -f "$selection" ]]; then
		cd "$(dirname "$selection")"
		$preview/file "$selection"
		continue
	fi

	echo "Unknown type: '$selection'"
done < "$NNN_FIFO"

