#!/usr/bin/env bash
set -e

function get_links() {
	for entry in $1/*; do

		# Skip unless directory symlink
		[[ -h "$entry" ]] || continue
		[[ -d "$entry" ]] || continue

		echo "$(basename "$entry") ->  $(readlink -f "$entry")"
	done
}

dir="$HOME/.links"
cddir="$(get_links "$dir" | column -t | fzf | awk 'END { print "'$dir'/"$1 }')"

[[ -z "$NNN_PIPE" ]] && { echo 'NNN_PIPE is not set'; exit 2; }
printf "%s" "0$(readlink -f "$cddir")" > "$NNN_PIPE"

