#!/usr/bin/env bash
# This is plugin for adding named bookmarks to `nnn`
#
# This plugin will search for all symlinks in $BOOKMARKS_DIR using `fzf`
BOOKMARKS_DIR="$HOME/.links"
set -e

# Check if NNN_PIPE is set
[[ -z "$NNN_PIPE" ]] && { echo 'NNN_PIPE is not set'; exit 2; }

# Get all directory symlinks
function get_links() {
	for entry in $1/*; do

		# Skip unless directory symlink
		[[ -h "$entry" ]] || continue
		[[ -d "$entry" ]] || continue

		echo "$(basename "$entry") ->  $(readlink -f "$entry")"
	done | column -t
}

# Choose symlink with fzf
cddir="$(get_links "$BOOKMARKS_DIR" | fzf | awk 'END { print "'$BOOKMARKS_DIR'/"$1 }')"

# Writing result to NNN_PIPE will change nnn's active directory
# https://github.com/jarun/nnn/tree/master/plugins#send-data-to-nnn
context=0
printf "%s" "${context}c$(readlink -f "$cddir")" > "$NNN_PIPE"

