#!/usr/bin/env bash
# This is plugin for adding named bookmarks to `nnn`
#
# This plugin will search for all symlinks in $BOOKMARKS_DIR using `fzf`
BOOKMARKS_DIR="$HOME/.links"
set -e

# Check if NNN_PIPE is set
if [[ -z "$NNN_PIPE" ]]; then
	echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
	exit 2
fi

# Get all directory symlinks
function get_links() {
	for entry in $1/*; do

		# Skip unless directory symlink
		[[ -h "$entry" ]] || continue
		[[ -d "$entry" ]] || continue

		printf "%20s -> %s\n" "$(basename "$entry")" "$(readlink -f "$entry")"
	done | fzf | awk 'END { print "'$BOOKMARKS_DIR'/"$1 }'
}

# Choose symlink with fzf
cddir="$(get_links "$BOOKMARKS_DIR")"

# Writing result to NNN_PIPE will change nnn's active directory
# https://github.com/jarun/nnn/tree/master/plugins#send-data-to-nnn
context=0
printf "%s" "${context}c$(readlink -f "$cddir")" > "$NNN_PIPE"

