#!/usr/bin/env bash
declare -r CURRENT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
preview_scripts="$CURRENT_DIR/preview_scripts"

if [[ -h "$1" ]]; then
	link="$(readlink -f "$1")"
	if [[ -d "$1" ]]; then
		print-header 'symlink dir'
		echo "$link"
		echo
		exec "$preview_scripts/dir" "$1"
	elif [[ -f "$1" ]]; then
		print-header 'symlink file'
		echo "$link"
		echo
		exec "$preview_scripts/file" "$1"
	else
		print-header 'symlink unknown'
		echo "$link"
	fi

elif [[ -d "$1" ]]; then
	exec "$preview_scripts/dir" "$1"
elif [[ -f "$1" ]]; then
	exec "$preview_scripts/file" "$1"
else
	echo "Unable to handle '$1'"
	exit 2
fi

