#!/usr/bin/env bash
if is-macos; then
	format='user,pid,ppid,%cpu,%mem,rss,vsz,etime,cputime,command'
else
	# TODO: Figure out how to make it display memory used in GB
	format='user:13,pid:7,ppid:7,%cpu,%mem,rsz:8,vsz:8,etime:12,cputime:8,command'
fi
exec ps -e -o "$format" \
	| grepm "$@" \
	| grep -v 'grep' \
	| sort -n -k 4 \
	| cutw \
	| hl "$USER"
