#!/usr/bin/env bash
prefix=".deleting.$(hostname).$$"
for src in $@; do
	[[ -e "$src" ]] || continue
	src="${src%/}"
	dest="$(dirname "$src")/$prefix.$(basename "$src")"
	mv "$src" "$dest"
	echo "rm -rf $src"
	rm -rf "$dest" &
done
