#!/usr/bin/env bash
[[ "$SENDER" = "volume_change" ]] || exit 0

VOLUME="$INFO"
case "$VOLUME" in
	[6-9][0-9]|100)   ICON="󰕾";;
	[3-5][0-9])       ICON="󰖀";;
	[1-9]|[1-2][0-9]) ICON="󰕿";;
	*) ICON="󰖁"
esac

label="$(printf '%02d%%' "$VOLUME")"
sketchybar --set "$NAME" icon="$ICON" label="$label"

