#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PATH="$SCRIPT_DIR:$PATH"

# Toggle mic mute when clicked
if [[ "$SENDER" = "mouse.clicked" ]]; then
	mic_volume="$(osascript -e 'input volume of (get volume settings)')"
	mac-mic-toggle
fi

#icon=''
icon=''

mic_volume="$(osascript -e 'input volume of (get volume settings)')"
if ((mic_volume==0)); then
	default_color="$(sketchybar --query defaults | jq -r .label.color)"
	color="$default_color"
else
	color="0xff$(theme red)"
fi

args=()
args+=(--set "${NAME:-mic}")
args+=(icon="$icon" icon.color="$color")
sketchybar "${args[@]}"

