#!/usr/bin/env bash

PERCENTAGE="$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)"
CHARGING="$(pmset -g batt | grep 'AC Power')"

[[ "$PERCENTAGE" = "" ]] && exit 0

case "${PERCENTAGE}" in
	9[0-9]|100) ICON="";;
	[6-8][0-9]) ICON="";;
	[3-5][0-9]) ICON="";;
	[1-2][0-9]) ICON="";;
	*) ICON=""
esac
ICON_COLOR='0xffff0000'

if [[ "$CHARGING" != "" ]]; then
	ICON=""
	ICON_COLOR='0xffffff00'
fi

sketchybar --set "$NAME" icon="$ICON" icon.color="$ICON_COLOR" label="${PERCENTAGE}%"

