#!/usr/bin/env bash
stack_index="$(yabai -m query --windows --window | jq '."stack-index"')"

args=()
args+=(--set "$NAME")

# If not in stack, turn off item
if ! ((stack_index)); then
	args+=(label="")
	args+=(drawing=off)

# If in stack, turn on item
else
	ICON='≡'
	COLOR='0xffff0000'
	args+=(drawing=on)
	args+=(label="$stack_index")
	args+=(label.color="$COLOR")
	args+=(icon="$ICON")
	args+=(icon.color="$COLOR")
fi

exec sketchybar "${args[@]}"

