#!/usr/bin/env bash
jabra_name='bluez_sink.30_50_75_38_65_58.a2dp_sink'
print-cmd pactl list short \| grep "$jabra_name"
pactl list short | grep "$jabra_name"
sink="$(pactl list short | awk "/$jabra_name\t/ { print \$1 }")"
print-run pactl set-default-sink "$sink"
