#!/usr/bin/env bash
# USAGE: sg "question"
# DESCRIPTION: Run sgpt

# Set your OpenAI API key
#OPENAI_API_KEY=''

export OPENAI_API_KEY
if [[ -z "$OPENAI_API_KEY" ]]; then
	print-warn 'OPENAI_API_KEY not set'
	#exit 2
fi

bin="/Users/$USER/Library/Python/3.11/bin"
PATH="$bin:$PATH"
#which sgpt
sgpt "$@"
#python3 -m venv shellgpt
#sgpt
