#!/usr/bin/env bash
declare -r CURRENT_DIR="$(realdir.py "${BASH_SOURCE[0]}")"
snippets_dir="$CURRENT_DIR/snippets"

result="$(for snippet in "$snippets_dir"/*; do
	[[ -d "$snippet" ]] && continue
	description="$(sed -n "s/.*DESCRIPTION:\s*\(.*\)/\1/p" "$snippet")"
	snippet_base="$(basename "$snippet")"
	printf '%-20s %s\n' "$snippet_base" "$description"
done | ,fzf snip)"
RETVAL=$?

if ((RETVAL)); then
	exit $RETVAL
fi

cat "$snippets_dir/${result%% *}"

