#!/usr/bin/env bash
session_name="${1?}"

# Create backup directory
tmux_cache="${XDG_CACHE_HOME:-$HOME/.cache}/tmux"
backup_dir="$tmux_cache/$session_name"
today="$(date +%Y%m%d)"
mkdir -p "$backup_dir"

# Write .yaml file
backup_yaml="$backup_dir/${today}.yaml"
tmux-session-info "$session_name" > "$backup_yaml"
RETVAL=$?

# Check if success
if ! ((RETVAL)); then
	echo "Saved to '$backup_yaml'"
fi

