#!/usr/bin/env bash
tmux_cache="${XDG_CACHE_HOME:-$HOME/.cache}/tmux"
for session in "$@"; do
	session_dir="$tmux_cache/backup/$session"
	if ! [[ -d "$session_dir" ]]; then
		echo "ERROR: '$session_dir' not found"
		continue
	fi
	unset -v newest
	for file in "$session_dir"/*; do
		[[ "$file" -nt "$newest" ]] && newest="$file"
	done
	print-run tmux-load-session "$session" "$newest"
done

