#!/usr/bin/env bash
flags='#{pane_top} #{pane_bottom} #{pane_left} #{pane_right} #{pane_height} #{pane_width}'
name="$(basename "$0")"
read -r top bottom left right height width <<< $(tmux display-message -p "$flags")
echo "USAGE        : read -r top bottom left right height width <<< \$($name)" 1>&2
echo "top left     : ($top,$left)" 1>&2
echo "botton right : ($bottom,$right)" 1>&2
echo "dimensions   : ${height}x$width" 1>&2
echo "$top $bottom $left $right $height $width"

