#!/usr/bin/env python3
# vim: ft=python noet ts=4 sw=0 sts

# TODO: Remove extra prints
# TODO: Output this is .yaml or .json

import re

ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')

with open('pane.txt', 'r') as f:
	lines = []
	for line in f:
		line = ansi_escape.sub('', line.rstrip('\n'))
		lines.append(line)

def find(lines, regex, group, hint = 'a'):
	matches = []
	for i, line in enumerate(lines):
		#print('--------------------------------------------------------------------------------')
		#print(line)
		m = re.match(regex, line)
		#print(m)
		if m:
			#print('MATCH')
			start, end = m.span(group)
			matches.append([hint, m.group(group), i, start, end])
	return matches

matches = []

# todd 755 bin main » <command>
matches += find(lines, r".*» *(.*)", 1, 'c')

# lrwxrwxrwx 1 todd group   11 Jan  1 23:59 file -> /path/to/file

# drwxrwxrwx 1 todd group    0 Jan  1 23:59 dir/

# drwxrwxrwx 1 todd group  10K Jan  1 23:59 file.txt

print(json.dumps(matches, indent=2))

