#!/usr/bin/env bash
# USAGE: tmux-pane-contents
# DESCRIPTION: Print the contents of the pane
pane_id="$1"

tmux_args=(capture-pane)
tmux_args+=(-p -e)
[[ -n "$pane_id" ]] && tmux_args+=(-t "$pane_id")
tmux "${tmux_args[@]}" 2>/dev/null

