#!/usr/bin/env ruby

require 'open3'
require 'yaml'

session_name = ARGV.first

# Get window/pane info from session
pane_info = ['window_index', 'window_name', 'window_layout', 'pane_current_path']
pane_format = pane_info.map { |info| "\#{#{info}}" }.join("\t")
session_info_cmd = ['tmux', 'list-panes', '-F', pane_format, '-s', '-t', session_name]
stdout, stderr, status = Open3.capture3(*session_info_cmd)
if status.exitstatus != 0
	$stderr.puts stderr unless stderr.empty?
	$stderr.puts "Command '#{session_info_cmd.join(' ')}' failed"
	exit status.exitstatus
end

# Generate hash of information
info = Hash.new
stdout.split("\n").each do |line|
	index, name, layout, path = line.split("\t")
	index = index.to_i
	info[index] ||= Hash.new
	info[index]['name'] = name
	info[index]['layout'] = layout
	info[index]['panes'] ||= Array.new
	info[index]['panes'].append(path)
end

# Print information
puts info.to_yaml

