#!/usr/bin/env bash
# exit 0 if tmux meets version

check_version="$1"
if [[ -z "$check_version" ]]; then
	cat <<-EOF
		USAGE: tmux-version VERSION
		Checks if VERSION >= current version
	EOF
	exit 1
fi

which tmux &> /dev/null || exit 1

# https://stackoverflow.com/questions/35016458/how-to-write-if-statement-in-tmux-conf-to-set-different-options-for-different-t
# - Support versions like tmux 2.4 tmux 2.4a tmux next-3.3
# - No bc command
# - Support Cygwin, macOS and Linux
current_version="$(tmux -V | cut -d' ' -f2)"
current_digits="$(echo "$current_version" | tr -d " |\-|.|[:alpha:]")"
check_digits="$(echo "$check_version" | tr -d " |\-|.|[:alpha:]")"

! (( current_digits < check_digits ))

