#!/usr/bin/env bash
if ! (type pactl >/dev/null); then
	notify-send -t 2000 -u critical 'pactl command not found. Run `sudo apt install pulseaudio`'
	exit 2
fi

cmd="$1"
case "$cmd" in
	up)
		pactl -- set-sink-volume @DEFAULT_SINK@ +5%
		pactl set-sink-mute @DEFAULT_SINK@ false
		;;
	down)
		pactl -- set-sink-volume @DEFAULT_SINK@ -5%
		pactl set-sink-mute @DEFAULT_SINK@ false
		;;
	mute)
		pactl set-sink-mute @DEFAULT_SINK@ toggle;;
	mic)
		amixer sset Capture toggle;;
	*)
		notify-send -t 2000 -u critical ",volume-pactl command '$cmd' not found"
		exit 2
		;;
esac

