#!/usr/bin/env bash
if ! (type pactl >/dev/null); then
	notify-send -t 2000 -u critical 'pactl command not found. Run `sudo apt install pulseaudio`'
	exit 2
fi

sink="@DEFAULT_SINK@"
#sink="0"

cmd="$1"
case "$cmd" in
	up)
		pactl -- set-sink-volume "$sink" +5%
		pactl set-sink-mute "$sink" false
		;;
	down)
		pactl -- set-sink-volume "$sink" -5%
		pactl set-sink-mute "$sink" false
		;;
	mute)
		pactl set-sink-mute "$sink" toggle;;
	mic)
		amixer sset Capture toggle;;
	*)
		notify-send -t 2000 -u critical ",volume-pactl command '$cmd' not found"
		exit 2
		;;
esac

# Popup notification for volume
notify-send \
	-t 400 \
	-u normal \
	-h string:x-canonical-private-synchronous:volume \
	"Volume (sink $sink)" \
	"$(volume-info-pactl "$sink")"

