#!/usr/bin/env bash
declare -r USAGE="USAGE: $(basename $0) <width> <height> <freq>"
width="$1"
height="$2"
freq="${3:-60}"
modeline="$(gtf "$width" "$height" "$freq" | sed -n 's/.*Modeline.*" *//p')"
#gtf "$width" "$height" "$freq"
mode="${width}x${height}_${freq}.00"
print-run xrandr --newmode "$mode" $modeline
