#!/usr/bin/env bash
# USAGE: yabai-work
# DESCRIPTION: TODO
#SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

initial_id="$(yabai -m query --windows --window | jq .id)"

declare -A apps
apps['iTerm2']=4
apps['ChatGPT']=7
apps['Gmail']=7
apps['Slack']=7
apps['Spotify']=8
apps['WhatsApp Web']=9

# Key to check
key_to_check="key2"

while read line; do
	#echo "line: $line"
	id="$(echo "$line" | jq -r .id 2>/dev/null)"
	app="$(echo "$line" | jq -r .app 2>/dev/null)"
	title="$(echo "$line" | jq -r .title 2>/dev/null)"
	[[ -z "$id" ]] && continue
	#echo "id:$id app:$app title:$title"

	if [[ -v apps[$app] ]]; then
		yabai -m window --focus "$id"
		yabai -m window --space "${apps[$app]}"
		continue
	elif [[ "$app" == "Google Chrome" ]]; then
		space_id="$(sed -n 's/\([1-9]\):.*/\1/p' <<<"$title")"
		if [[ -n "$space_id" ]]; then
			yabai -m window --focus "$id"
			yabai -m window --space "$space_id"
			continue
		fi
	fi
	#echo "id:$id app:$app title:$title"

done < <(yabai-ls-windows)

yabai -m window --focus "$initial_id"

