#!/usr/bin/env bash
# USAGE: yabai-ls-spaces
# DESCRIPTION: Print all spaces
#exec yabai -m query --spaces | jq .
exec yabai -m query --spaces | jq -c '.[] | {id,index,display,windows,"first-window","last-window","is-native-fullscren","stack-index"}'
