#!/usr/bin/env ruby
# vim: ft=ruby

require 'json'
require 'yaml'

yaml_file = ARGV.shift

if yaml_file.nil?
	$stderr.puts "USAGE: yaml2json <file.yaml>"
	exit 2
end

if not File.file?(yaml_file)
	$stderr.puts "ERROR: File '#{yaml_file}' not found"
	exit 2
end
content = File.read(yaml_file)

begin
	puts JSON.pretty_generate(YAML.load(content))
	# TODO: Add `jq` parsing
rescue Psych::SyntaxError => e
	p e
rescue => e
	p e
end

