#!/usr/bin/env bash
orig_stty="$(stty -g)"
stty -echo
function finish {
	stty "$orig_stty"
}
trap finish EXIT

echo "${@:-Yes or no?} (y/n)"
while true; do
	read -s -n 1 -e reply < /dev/tty
	case "$reply" in
		[Yy]) exit 0;;
		[Nn]) exit 1;;
	esac
done
