#!/usr/bin/env bash

# Check if interactive
# Fixes this:
#   stty: 'standard input': Inappropriate ioctl for device
if [[ $- == *i* ]]; then
	orig_stty="$(stty -g)"
	stty -echo
	function finish {
		[[ -n "$orig_tty" ]] && stty "$orig_stty"
	}
	trap finish EXIT
fi

# Ask
cecho --bold --fg yellow "${@:-Yes or no?} (y/n)"

# Wait for valid response
while true; do
	read -s -n 1 -e reply < /dev/tty
	case "$reply" in
		[Yy]) exit 0;;
		[Nn]) exit 1;;
	esac
done

