#!/usr/bin/env bash

# Check if interactive
# Fixes this:
#   stty: 'standard input': Inappropriate ioctl for device
#if [[ $- == *i* ]]; then
#	orig_stty="$(stty -g)"
#	stty -echo
#	function finish {
#		[[ -n "$orig_tty" ]] && stty "$orig_stty"
#	}
#	trap finish EXIT
#fi

# Ask
cecho -n --bold --fg yellow "${@:-Yes or no?} (y/n) "

# Wait for valid response
while true; do
	read -r -s -n 1 reply </dev/tty
	case "$reply" in
		[Yy]) cecho --bold --fg green "y"; exit 0;;
		[Nn]) cecho --bold --fg red   "n"; exit 1;;
	esac
done

