#!/usr/bin/env bash
dir=$(echo $@ | awk '{print $NF}')
[[ -d $dir ]] || { echo "Directory '$dir' does not exist"; exit 2; }
echo -e "\e[33;1m==> directory info  <==\e[0m"
export LC_ALL=C
ls -ldh  --color=always $(readlink -f $dir)
echo
ls -l --color=always $dir | tail

