#!/usr/bin/env bash
format="#{pane_id} #{session_name}.#{window_name}[#{window_index}].#{pane_index}"
format+=" #{pane_current_command} #{pane_current_path}"
while read pane_id window cmd path; do
	printf "%-6s  %-20s  %s\n" $pane_id $window "$cmd $path"
done < <(tmux list-panes -a -F "$format")

