#!/usr/bin/env bash
dir=$(echo $@ | awk '{print $NF}')
[[ -d $dir ]] || { echo "Directory '$dir' does not exist"; exit 2; }
export LC_ALL=C

function get_user() {
	owner="$(stat -c '%U' "$1")"
	if [[ "$owner" == "$USER" ]]; then
		echo -e "\e[32;1m$owner\e[0m"
	else
		echo -e "\e[31;1m$owner\e[0m"
	fi
}

modified="$(stat -c '%Z' "$dir")"
echo -e "\e[33;1mDIRECTORY:\e[0m '$dir'"
echo -e "\e[33;1mOWNER:    \e[0m $(get_user "$dir")"
echo -e "\e[33;1mGROUP:    \e[0m $(stat -c '%G' "$dir")"
echo -e "\e[33;1mACCESS:   \e[0m $(stat -c '%a' "$dir")"
echo -e "\e[33;1mMODIFIED: \e[0m $(date -d @$modified +'%Y-%m-%d %T')"

if [[ -f "$dir/RESULT.xml" ]]; then
	echo
	echo -e "\e[33;1mBAMBOO RESULTS:\e[0m "
	for child_dir in $dir/*; do
		[[ -d "$child_dir" ]] || continue
		echo -e "$(get_user "$(readlink -f "$child_dir")") $(basename "$child_dir") \e[31;1m$(grep result "$child_dir/result.yaml" 2>/dev/null)\e[0m"
	done
	exit
fi

if [[ -f "$dir/result.yaml" ]]; then
	echo
	echo "RESULT:"
	grep result "$dir/result.yaml"
fi

echo
ls -l --color=always $dir | tail

