#!/usr/bin/env bash

# Check file
file="$1"
[[ -f "$file" ]] || { echo "File '$file' not found"; exit 2; }

# Print info
info="$(file "$file")"
echo -e "\e[33;1m==> file info <==\e[0m"
echo "$info"
ls -lh "$file"

# TODO: Figure out what to do with this
#file $file | awk '{$1=""; print}' | grep -v text && exit 0

# TODO: Figure out how to get number of lines in preview window
# `tput lines` returns full fzf size
#lines=$(tput lines)

# grep things and print in color
esc=$(printf '\033')
function colorgrep() {
	local color="$1"
	shift
	sed \
		-e "s/^/${esc}[${color}m/" \
		-e "s/\$/${esc}[0m/" \
		"$@"
}


# ==============================================================================
# PRINT FILE CONTENT
# ==============================================================================
# REVISIT: Look into `https://github.com/sharkdp/bat`

# Handle UART files
if [[ "$file" =~ uart.* ]]; then
	echo -e "\e[33;1m==> uart file <==\e[0m"
	colorgrep '31;1' -n -e '/Failing at test/p' "$file"
	tail -n 10 "$file" | strings
	echo -e "\e[33;1m==> end <==\e[0m"
	exit

# Handle JSON files
elif [[ "$file" =~ .*\.json ]]; then
	echo -e "\e[33;1m==> json <==\e[0m"
	if (which jq &>/dev/null); then
		jq -C . "$file" | head -n 30
	else
		echo -e "\e[31mjq not found\e[0m"
		head -n 30 "$file"
	fi
	echo -e "\e[31m...\e[0m"
	echo -e "\e[33;1m==> end <==\e[0m"
	exit

elif [[ "$file" =~ .*\.log ]]; then
	echo -e "\e[33;1m==> head <==\e[0m"
	head -n 5 $file
	echo -e "\e[31m...\e[0m"
	tail -n 10 $file

# Print generic info
else
	echo -e "\e[33;1m==> head <==\e[0m"
	head -n 50 $file
	echo -e "\e[31m...\e[0m"
fi

# End of preview
echo -e "\e[33;1m==> end <==\e[0m"

