#!/usr/bin/env bash

# Check file
file="$1"
[[ -f "$file" ]] || { echo "File '$file' not found"; exit 2; }

# Print info
info="$(file -b "$file")"
mimetype="$(file -b --mime-type "$file")"
echo -e "\e[33;1m==> file info <==\e[0m"
echo "MIME type: '$mimetype'"
echo "$info"
ls -lh "$file"


if [[ "$mimetype" =~ ^application ]]; then
	exit
elif [[ "$mimetype" =~ ^audio ]]; then
	exit
elif [[ "$mimetype" =~ ^image ]]; then
	exit
fi

# TODO: Figure out how to get number of lines in preview window
# `tput lines` returns full fzf size
#lines=$(tput lines)
width=$(tput cols)
function cutw() {
	cut -c 1-$width
}
function headn() {
	local n=$1
	shift
	head -n $n $@ | cutw
}
function tailn() {
	local n=$1
	shift
	tail -n $n $@ | cutw
}

# grep things and print in color
esc=$(printf '\033')
function colorgrep() {
	local color="$1"
	shift
	sed \
		-e "s/^/${esc}[${color}m/" \
		-e "s/\$/${esc}[0m/" \
		"$@"
}


# ==============================================================================
# PRINT FILE CONTENT
# ==============================================================================
# REVISIT: Look into `https://github.com/sharkdp/bat`

# Handle UART files
if [[ "$file" =~ uart.* ]]; then
	echo -e "\e[33;1m==> uart file <==\e[0m"
	if (grep 'Failing at test' "$file" &> /dev/null); then
		awk '
			/^Test 0/ {part=1; line=$0}
			(part==1) && (!/^Test 0/) {print line; part=2}
			/^Failing at test/ {part=3}
			(part==2) {print}
		' "$file"
		colorgrep '31;1' -n -e '/Failing at test/p' "$file"
		echo -e "\e[33m...\e[0m"
	fi
	tailn 10 "$file" | strings | cutw
	echo -e "\e[33;1m==> end <==\e[0m"
	exit

# Handle JSON files
elif [[ "$file" =~ .*\.json ]]; then
	echo -e "\e[33;1m==> json <==\e[0m"
	if (which jq &>/dev/null); then
		jq -C . "$file" | headn 30
	else
		echo -e "\e[31mjq not found\e[0m"
		headn 30 "$file"
	fi
	echo -e "\e[31m...\e[0m"
	echo -e "\e[33;1m==> end <==\e[0m"
	exit

elif [[ "$file" =~ .*\.log ]]; then
	echo -e "\e[33;1m==> contents <==\e[0m"
	headn 5 $file
	echo -e "\e[31m...\e[0m"
	tailn 10 $file

# Print generic info
else
	echo -e "\e[33;1m==> head <==\e[0m"
	headn 50 $file
	echo -e "\e[31m...\e[0m"
fi

# End of preview
echo -e "\e[33;1m==> end <==\e[0m"

