#!/usr/bin/env bash
declare -r CURRENT_DIR="$(dirname "$(realpath.py "${BASH_SOURCE[0]}")")"

# TODO: Should probably shift until last arg and use $1
dir="$(echo "$@" | awk '{print $NF}')"
dir="$(echo "$dir" 2>/dev/null | sed "s|\$GIT_TOP|$(git-top)|")"
[[ -d "$dir" ]] || { cecho --fg red --bold "Directory '$dir' does not exist"; exit 2; }
cd "$dir"
export LC_ALL=C

function get_user() {
	owner="$(stat -c '%U' "$1")"
	if [[ "$owner" == "$USER" ]]; then
		echo -e "\e[32;1m$owner\e[0m"
	else
		echo -e "\e[31;1m$owner\e[0m"
	fi
}

function get_result() {
	local dir="$1"
	result_file="$(ls -1 "$dir"/result*.yaml 2>/dev/null | tail -n 1)"
	if [[ -f "$result_file" ]]; then
		grep -m 1  result "$result_file"
	else
		echo 'RESULT NOT FOUND'
	fi
}

modified="$(stat -c '%Z' .)"
echo -e "\e[33;1mDIRECTORY:\e[0m '$dir'"
echo -e "\e[33;1mOWNER:    \e[0m $(get_user .)"
echo -e "\e[33;1mGROUP:    \e[0m $(stat -c '%G' .)"
echo -e "\e[33;1mACCESS:   \e[0m $(stat -c '%a' .)"
echo -e "\e[33;1mMODIFIED: \e[0m $(date -d @$modified +'%Y-%m-%d %T')"

if [[ -f "$dir/RESULT.xml" ]]; then
	echo
	echo -e "\e[33;1mBAMBOO RESULTS:\e[0m "
	for child_dir in $dir/*; do
		[[ -d "$child_dir" ]] || continue
		result="$(get_result "$child_dir")"
		echo -e "$(get_user "$(realpath.py "$child_dir")") $(basename "$child_dir") \e[31;1m$result\e[0m"
	done
	exit
fi

result="$(get_result "$dir")"
if [[ -n "$result" ]]; then
	echo
	cecho --fg yellow --bold "RESULT:"
	echo "$result"
fi

# Setup
#declare -r CURRENT_DIR="$(dirname "$(realpath.py "${BASH_SOURCE[0]}")")"
#source "$CURRENT_DIR/lib.bash"

# Contents
echo
cecho --fg yellow --bold "CONTENTS:"
ls -lth --color=always

if [[ -e "uart.log" ]]; then
	echo
	"$CURRENT_DIR/uart" "uart.log"
	exit
fi

if [[ -e "test.log" ]]; then
	echo
	"$CURRENT_DIR/testlog" "test.log"
	exit
fi

