#!/usr/bin/env bash
dir="$(echo "$@" | awk '{print $NF}')"
[[ -d "$dir" ]] || { echo "Directory '$dir' does not exist"; exit 2; }
cd "$dir"
export LC_ALL=C

function get_user() {
	owner="$(stat -c '%U' "$1")"
	if [[ "$owner" == "$USER" ]]; then
		echo -e "\e[32;1m$owner\e[0m"
	else
		echo -e "\e[31;1m$owner\e[0m"
	fi
}

function get_result() {
	local dir="$1"
	result_file="$(ls -1 "$dir"/result*.yaml 2>/dev/null | tail -n 1)"
	if [[ -f "$result_file" ]]; then
		grep -m 1  result "$result_file"
	else
		echo 'RESULT NOT FOUND'
	fi
}

modified="$(stat -c '%Z' "$dir")"
echo -e "\e[33;1mDIRECTORY:\e[0m '$dir'"
echo -e "\e[33;1mOWNER:    \e[0m $(get_user "$dir")"
echo -e "\e[33;1mGROUP:    \e[0m $(stat -c '%G' "$dir")"
echo -e "\e[33;1mACCESS:   \e[0m $(stat -c '%a' "$dir")"
echo -e "\e[33;1mMODIFIED: \e[0m $(date -d @$modified +'%Y-%m-%d %T')"

if [[ -f "$dir/RESULT.xml" ]]; then
	echo
	echo -e "\e[33;1mBAMBOO RESULTS:\e[0m "
	for child_dir in $dir/*; do
		[[ -d "$child_dir" ]] || continue
		result="$(get_result "$child_dir")"
		echo -e "$(get_user "$(readlink -f "$child_dir")") $(basename "$child_dir") \e[31;1m$result\e[0m"
	done
	exit
fi

result="$(get_result "$dir")"
if [[ -n "$result" ]]; then
	echo
	echo -e "\e[33;1mRESULT:\e[0m"
	echo "$result"
fi

echo
ls -lh --color=always $dir | tail

