#!/usr/bin/env bash

# Check file
file="$1"
[[ -f "$file" ]] || { echo "File '$file' not found"; exit 2; }

# Print info
info="$(file -b "$file")"
mimetype="$(file -b --mime-type "$file")"
print-header 'file info'
echo "MIME type: '$mimetype'"
echo "$info"
ls -lh "$file"


if [[ "$mimetype" =~ ^application ]]; then
	exit
elif [[ "$mimetype" =~ ^audio ]]; then
	exit
elif [[ "$mimetype" =~ ^image ]]; then
	exit
fi

# Setup
declare -r CURRENT_DIR="$(dirname "$(realpath.py "${BASH_SOURCE[0]}")")"
source "$CURRENT_DIR/lib.bash"


# ==============================================================================
# PRINT FILE CONTENT
# ==============================================================================
# REVISIT: Look into `https://github.com/sharkdp/bat`

# Handle UART files
if [[ "$file" =~ uart.* ]]; then
	"$CURRENT_DIR/uart" "$file"
	exit

# Handle JSON files
elif [[ "$file" =~ .*\.json ]]; then
	print-header 'json'
	if (which jq &>/dev/null); then
		jq -C . "$file" | headn 30
	else
		echo -e "\e[31mjq not found\e[0m"
		headn 30 "$file"
	fi
	echo -e "\e[31m...\e[0m"
	print-header 'end'
	exit

elif [[ "$file" =~ .*\.log ]]; then
	print-header 'errors'
	grep -i error: "$file" | cutw
	print-header 'contents'
	headn 5 $file
	echo -e "\e[31m...\e[0m"
	tailn 10 $file

# Print generic info
else
	print-header 'head'
	headn 50 $file
	echo -e "\e[31m...\e[0m"
fi

# End of preview
print-header 'end'

