#!/usr/bin/env bash

# Add --cached for staged files

exit

# ==============================================================================
# FORGIT EXAMPLE
# ==============================================================================
extract="
	sed 's/^.*]  //' |
	sed 's/.* -> //' |
	sed -e 's/^\\\"//' -e 's/\\\"\$//'"
preview="
	file=\$(echo {} | $extract)
	if (git status -s -- \$file | grep '^??') &>/dev/null; then  # diff with /dev/null for untracked files
		git diff --color=always --no-index -- /dev/null \$file | $forgit_pager | sed '2 s/added:/untracked:/'
	else
		git diff --color=always -- \$file | $forgit_pager
	fi"

