#!/usr/bin/env bash
declare -r CURRENT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# Check file
file="$1"
[[ -f "$file" ]] || exit $?

source "$CURRENT_DIR/lib.bash"

print-header 'uart file'
if (grep 'Failing at test' "$file" &> /dev/null); then
	awk '
		/^Test 0/ {part=1; line=$0}
		(part==1) && (!/^Test 0/) {print line; part=2}
		/Failing at test/ {part=3}
		(part==2) {print}
	' "$file"
	colorgrep '31;1' -n -e '/Failing at test/p' "$file"
	echo -e "\e[33m...\e[0m"
fi
tailn 10 "$file" | strings | cutw
print-header 'end'

